# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-11 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swh.web.common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveoriginrequest',
            name='visit_date',
            field=models.DateTimeField(null=True),
        ),
    ]
