# Generated by Django 2.2.15 on 2021-01-06 13:27

# Adds indexes to the Save Code Now tables.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swh_web_common", "0007_save_request_task_status_fix_typo"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="saveauthorizedorigin",
            index=models.Index(fields=["url"], name="save_author_url_3e4e9d_idx"),
        ),
        migrations.AddIndex(
            model_name="saveoriginrequest",
            index=models.Index(
                fields=["origin_url", "status"], name="save_origin_origin__b46350_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saveunauthorizedorigin",
            index=models.Index(fields=["url"], name="save_unauth_url_c008fc_idx"),
        ),
    ]
