# Generated by Django 2.2.27 on 2022-02-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swh_web_auth", "0004_usermailmap"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMailmapEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(max_length=50)),
                ("request_type", models.CharField(max_length=50)),
                ("request", models.TextField()),
                ("successful", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "user_mailmap_event",
            },
        ),
        migrations.AddIndex(
            model_name="usermailmapevent",
            index=models.Index(
                fields=["timestamp"], name="user_mailma_timesta_1f7aef_idx"
            ),
        ),
    ]
