# Copyright (C) 2021 The Software Heritage developers
# See the AUTHORS file at the top-level directory of this distribution
# License: GNU General Public License version 3, or any later version
# See top-level LICENSE file for more information
# Generated by Django 2.2.20 on 2021-05-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swh_web_save_code_now", "0009_saveoriginrequest_visit_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="saveoriginrequest",
            name="user_id",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
