SWH_WEB_UI=./bin/swh-web-ui-dev
FLAG=-v
NOSEFLAGS=-v -s

run-test:
	$(SWH_WEB_UI) $(FLAG) --config ./resources/test/webapp.ini

run: # works with the default ~/.config/swh/web-ui.ini file
	$(SWH_WEB_UI) $(FLAG)
