[tool.black]
target-version = ['py37']
exclude = 'swh/web/tests/resources/contents'

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
force_sort_within_sections = true
known_django = 'django,rest_framework'
sections = 'FUTURE,STDLIB,THIRDPARTY,DJANGO,FIRSTPARTY,LOCALFOLDER'

[tool.djlint]
# https://www.djlint.com/docs/linter/#rules
ignore = "H006,H020,H021,H023,H029,H030,H031"
indent = 2
blank_line_after_tag = "endcomment,extends,load,endblock"
max_line_length = 100
