# Generated by Django 2.2.27 on 2022-03-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("swh_web_add_forge_now", "0003_request_submitter_forward_username"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="request",
            table="add_forge_request",
        ),
        migrations.AlterModelTable(
            name="requesthistory",
            table="add_forge_request_history",
        ),
    ]
