# Copyright (C) 2020-2022  The Software Heritage developers
# See the AUTHORS file at the top-level directory of this distribution
# License: GNU Affero General Public License version 3, or any later version
# See top-level LICENSE file for more information

from django.db import models


class OIDCUserOfflineTokens(models.Model):
    """
    Model storing encrypted bearer tokens generated by users.
    """

    user_id = models.CharField(max_length=50)
    creation_date = models.DateTimeField(auto_now_add=True)
    offline_token = models.BinaryField()

    class Meta:
        app_label = "swh_web_auth"
        db_table = "oidc_user_offline_tokens"


class UserMailmap(models.Model):
    """
    Model storing mailmap settings submitted by users.
    """

    user_id = models.CharField(max_length=50, null=True)
    """Optional user id from Keycloak"""

    from_email = models.TextField(unique=True, null=False)
    """Email address to find author in the archive"""

    from_email_verified = models.BooleanField(default=False)
    """Indicates if the from email has been verified"""

    from_email_verification_request_date = models.DateTimeField(null=True)
    """Last from email verification request date"""

    display_name = models.TextField(null=False)
    """Display name to use for the author instead of the archived one"""

    display_name_activated = models.BooleanField(default=False)
    """Indicates if the new display name should be used"""

    to_email = models.TextField(null=True)
    """Optional new email to use in the display name instead of the archived one"""

    to_email_verified = models.BooleanField(default=False)
    """Indicates if the to email has been verified"""

    to_email_verification_request_date = models.DateTimeField(null=True)
    """Last to email verification request date"""

    mailmap_last_processing_date = models.DateTimeField(null=True)
    """Last mailmap synchronisation date with swh-storage"""

    last_update_date = models.DateTimeField(auto_now=True)
    """Last date that mailmap model was updated"""

    class Meta:
        app_label = "swh_web_auth"
        db_table = "user_mailmap"
